### ISSUE TITLE
Que matricular en 3 semestre?

### ISSUE THREAD

**Issue by vamphook972** [lapiceroazul4/Ingenieria-Datos-IA-Roadmap-UAO#4]
Buenas mi nombre es victor y estoy en segundo semestre. Tengo una pregunta sobre las materias de 3 y 4 semestre, ya que muchos me han dicho que deberia matricular sistemas operativos antes que redes e infrastructuras, pero no se que tan cierto sea eso o que tan conveniente sea, debido que estas materias tienen diferente cantidad de creditos.

**Comment by lapiceroazul4** [comment]
Hola Victor, te cuento. 
En redes e infra. apartir del 2do corte vas a tener que desarrollar cosas como:

- Arquitectura de microservicios 
- Aplicativo web (Frontend & Backend) 

En el curso esto se hace con Maquinas Virtuales (VM), y estás maquinas virtuales tienen como sistema operativo Ubuntu, de ahí la sugerencia que hacen algunas personas de ver primero Sistemas Operativos, pero realmente esto no es estrictamente necesario... 

En lo personal considero que los conocimientos que "necesitas" de sistemas operativos para ver redes son bastante básicos y puedes adquirirlos en 1 semana de estudio, asi que por mi parte te diria que escojas lo que mejor se ajuste a tu caso, si puedes verlas juntas bien, sino, tampoco tienes que preocuparte..

Aqui te dejo algunos recursos que puedes revisar por si quieres conocer un poco sobre estos temas 

- [Virtual Machines](https://azure.microsoft.com/es-mx/resources/cloud-computing-dictionary/what-is-a-virtual-machine#:~:text=Estas%20son%20algunas%20formas%20de,escenarios%20de%20desarrollo%20y%20pruebas.) 
- [VirtualBox](https://www.geeknetic.es/VirtualBox/que-es-y-para-que-sirve)
- [Conociendo Ubuntu](https://www.hostinger.co/tutoriales/que-es-ubuntu) 
- [Comandos básicos de Linux](https://www.dreamhost.com/blog/es/comandos-linux-que-debes-conocer/)
- [Cómo instalar Ubuntu en VirtualBox](https://www.youtube.com/watch?v=hLfVO0GwheU)

> **Voy a dejar el Issue abierto esta semana por si tienes alguna duda adicional o por si alguna otra persona quiere darte su punto de vista**

**Comment by RJuanJo** [comment]
Hola Victor, cordial saludo.
Como tal puedes tomar varias opciones ninguna va ser mejor que otra todo depende de ti y como veas tus capacidades. El tema de SOs y Redes puedes ver incluso ambas a la vez o primero una y luego la otra.
Asimismo puedes optar por ver antes almacenamiento que redes, actualmente ambas son buenas opciones.

Si te das el tiempo recomiendo la pagina de **[Jon Mircha](https://jonmircha.com/cursos)**. Tiene muy buena información y cursos que te van servir tanto para redes como para almacenamiento.
